/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as EulaRouteImport } from './routes/eula'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests/index'
import { Route as AuthenticatedPlatformsIndexRouteImport } from './routes/_authenticated/platforms/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedVendorsVendorIdRouteImport } from './routes/_authenticated/vendors/$vendorId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedRevenueListRouteImport } from './routes/_authenticated/revenue/list'
import { Route as AuthenticatedRevenueReportIdRouteImport } from './routes/_authenticated/revenue/$reportId'
import { Route as AuthenticatedPayoutsPayoutIdRouteImport } from './routes/_authenticated/payouts/$payoutId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedVendorStatsIndexRouteImport } from './routes/_authenticated/vendor/stats/index'
import { Route as AuthenticatedVendorProfileIndexRouteImport } from './routes/_authenticated/vendor/profile/index'
import { Route as AuthenticatedVendorPayoutsIndexRouteImport } from './routes/_authenticated/vendor/payouts/index'
import { Route as AuthenticatedVendorStatsReportRouteImport } from './routes/_authenticated/vendor/stats/report'
import { Route as AuthenticatedVendorStatsStatsRouteImport } from './routes/_authenticated/vendor/stats/$stats'
import { Route as AuthenticatedVendorPayoutsPayoutidRouteImport } from './routes/_authenticated/vendor/payouts/$payoutid'

const AuthenticatedPayoutsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/payouts/',
)()
const AuthenticatedRevenueUploadLazyRouteImport = createFileRoute(
  '/_authenticated/revenue/upload',
)()
const AuthenticatedRevenueManualLazyRouteImport = createFileRoute(
  '/_authenticated/revenue/manual',
)()

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EulaRoute = EulaRouteImport.update({
  id: '/eula',
  path: '/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayoutsIndexLazyRoute =
  AuthenticatedPayoutsIndexLazyRouteImport.update({
    id: '/payouts/',
    path: '/payouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/payouts/index.lazy').then((d) => d.Route),
  )
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/vendor/',
    path: '/vendor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformsIndexRoute =
  AuthenticatedPlatformsIndexRouteImport.update({
    id: '/platforms/',
    path: '/platforms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevenueUploadLazyRoute =
  AuthenticatedRevenueUploadLazyRouteImport.update({
    id: '/revenue/upload',
    path: '/revenue/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/revenue/upload.lazy').then((d) => d.Route),
  )
const AuthenticatedRevenueManualLazyRoute =
  AuthenticatedRevenueManualLazyRouteImport.update({
    id: '/revenue/manual',
    path: '/revenue/manual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/revenue/manual.lazy').then((d) => d.Route),
  )
const AuthenticatedVendorsVendorIdRoute =
  AuthenticatedVendorsVendorIdRouteImport.update({
    id: '/vendors/$vendorId',
    path: '/vendors/$vendorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRevenueListRoute =
  AuthenticatedRevenueListRouteImport.update({
    id: '/revenue/list',
    path: '/revenue/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevenueReportIdRoute =
  AuthenticatedRevenueReportIdRouteImport.update({
    id: '/revenue/$reportId',
    path: '/revenue/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayoutsPayoutIdRoute =
  AuthenticatedPayoutsPayoutIdRouteImport.update({
    id: '/payouts/$payoutId',
    path: '/payouts/$payoutId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorStatsIndexRoute =
  AuthenticatedVendorStatsIndexRouteImport.update({
    id: '/vendor/stats/',
    path: '/vendor/stats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorProfileIndexRoute =
  AuthenticatedVendorProfileIndexRouteImport.update({
    id: '/vendor/profile/',
    path: '/vendor/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorPayoutsIndexRoute =
  AuthenticatedVendorPayoutsIndexRouteImport.update({
    id: '/vendor/payouts/',
    path: '/vendor/payouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorStatsReportRoute =
  AuthenticatedVendorStatsReportRouteImport.update({
    id: '/vendor/stats/report',
    path: '/vendor/stats/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorStatsStatsRoute =
  AuthenticatedVendorStatsStatsRouteImport.update({
    id: '/vendor/stats/$stats',
    path: '/vendor/stats/$stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorPayoutsPayoutidRoute =
  AuthenticatedVendorPayoutsPayoutidRouteImport.update({
    id: '/vendor/payouts/$payoutid',
    path: '/vendor/payouts/$payoutid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/eula': typeof EulaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/payouts/$payoutId': typeof AuthenticatedPayoutsPayoutIdRoute
  '/revenue/$reportId': typeof AuthenticatedRevenueReportIdRoute
  '/revenue/list': typeof AuthenticatedRevenueListRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/revenue/manual': typeof AuthenticatedRevenueManualLazyRoute
  '/revenue/upload': typeof AuthenticatedRevenueUploadLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/platforms': typeof AuthenticatedPlatformsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/payouts': typeof AuthenticatedPayoutsIndexLazyRoute
  '/vendor/payouts/$payoutid': typeof AuthenticatedVendorPayoutsPayoutidRoute
  '/vendor/stats/$stats': typeof AuthenticatedVendorStatsStatsRoute
  '/vendor/stats/report': typeof AuthenticatedVendorStatsReportRoute
  '/vendor/payouts': typeof AuthenticatedVendorPayoutsIndexRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileIndexRoute
  '/vendor/stats': typeof AuthenticatedVendorStatsIndexRoute
}
export interface FileRoutesByTo {
  '/eula': typeof EulaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/payouts/$payoutId': typeof AuthenticatedPayoutsPayoutIdRoute
  '/revenue/$reportId': typeof AuthenticatedRevenueReportIdRoute
  '/revenue/list': typeof AuthenticatedRevenueListRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/revenue/manual': typeof AuthenticatedRevenueManualLazyRoute
  '/revenue/upload': typeof AuthenticatedRevenueUploadLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/platforms': typeof AuthenticatedPlatformsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/payouts': typeof AuthenticatedPayoutsIndexLazyRoute
  '/vendor/payouts/$payoutid': typeof AuthenticatedVendorPayoutsPayoutidRoute
  '/vendor/stats/$stats': typeof AuthenticatedVendorStatsStatsRoute
  '/vendor/stats/report': typeof AuthenticatedVendorStatsReportRoute
  '/vendor/payouts': typeof AuthenticatedVendorPayoutsIndexRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileIndexRoute
  '/vendor/stats': typeof AuthenticatedVendorStatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/eula': typeof EulaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/payouts/$payoutId': typeof AuthenticatedPayoutsPayoutIdRoute
  '/_authenticated/revenue/$reportId': typeof AuthenticatedRevenueReportIdRoute
  '/_authenticated/revenue/list': typeof AuthenticatedRevenueListRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/_authenticated/revenue/manual': typeof AuthenticatedRevenueManualLazyRoute
  '/_authenticated/revenue/upload': typeof AuthenticatedRevenueUploadLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/platforms/': typeof AuthenticatedPlatformsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/payouts/': typeof AuthenticatedPayoutsIndexLazyRoute
  '/_authenticated/vendor/payouts/$payoutid': typeof AuthenticatedVendorPayoutsPayoutidRoute
  '/_authenticated/vendor/stats/$stats': typeof AuthenticatedVendorStatsStatsRoute
  '/_authenticated/vendor/stats/report': typeof AuthenticatedVendorStatsReportRoute
  '/_authenticated/vendor/payouts/': typeof AuthenticatedVendorPayoutsIndexRoute
  '/_authenticated/vendor/profile/': typeof AuthenticatedVendorProfileIndexRoute
  '/_authenticated/vendor/stats/': typeof AuthenticatedVendorStatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/eula'
    | '/privacy-policy'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/payouts/$payoutId'
    | '/revenue/$reportId'
    | '/revenue/list'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/vendors/$vendorId'
    | '/revenue/manual'
    | '/revenue/upload'
    | '/help-center'
    | '/platforms'
    | '/requests'
    | '/settings/'
    | '/vendor'
    | '/vendors'
    | '/payouts'
    | '/vendor/payouts/$payoutid'
    | '/vendor/stats/$stats'
    | '/vendor/stats/report'
    | '/vendor/payouts'
    | '/vendor/profile'
    | '/vendor/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/eula'
    | '/privacy-policy'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/payouts/$payoutId'
    | '/revenue/$reportId'
    | '/revenue/list'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/vendors/$vendorId'
    | '/revenue/manual'
    | '/revenue/upload'
    | '/help-center'
    | '/platforms'
    | '/requests'
    | '/settings'
    | '/vendor'
    | '/vendors'
    | '/payouts'
    | '/vendor/payouts/$payoutid'
    | '/vendor/stats/$stats'
    | '/vendor/stats/report'
    | '/vendor/payouts'
    | '/vendor/profile'
    | '/vendor/stats'
  id:
    | '__root__'
    | '/_authenticated'
    | '/eula'
    | '/privacy-policy'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/payouts/$payoutId'
    | '/_authenticated/revenue/$reportId'
    | '/_authenticated/revenue/list'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/vendors/$vendorId'
    | '/_authenticated/revenue/manual'
    | '/_authenticated/revenue/upload'
    | '/_authenticated/help-center/'
    | '/_authenticated/platforms/'
    | '/_authenticated/requests/'
    | '/_authenticated/settings/'
    | '/_authenticated/vendor/'
    | '/_authenticated/vendors/'
    | '/_authenticated/payouts/'
    | '/_authenticated/vendor/payouts/$payoutid'
    | '/_authenticated/vendor/stats/$stats'
    | '/_authenticated/vendor/stats/report'
    | '/_authenticated/vendor/payouts/'
    | '/_authenticated/vendor/profile/'
    | '/_authenticated/vendor/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EulaRoute: typeof EulaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eula': {
      id: '/eula'
      path: '/eula'
      fullPath: '/eula'
      preLoaderRoute: typeof EulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts/': {
      id: '/_authenticated/payouts/'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platforms/': {
      id: '/_authenticated/platforms/'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedPlatformsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue/upload': {
      id: '/_authenticated/revenue/upload'
      path: '/revenue/upload'
      fullPath: '/revenue/upload'
      preLoaderRoute: typeof AuthenticatedRevenueUploadLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue/manual': {
      id: '/_authenticated/revenue/manual'
      path: '/revenue/manual'
      fullPath: '/revenue/manual'
      preLoaderRoute: typeof AuthenticatedRevenueManualLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$vendorId': {
      id: '/_authenticated/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof AuthenticatedVendorsVendorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/revenue/list': {
      id: '/_authenticated/revenue/list'
      path: '/revenue/list'
      fullPath: '/revenue/list'
      preLoaderRoute: typeof AuthenticatedRevenueListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revenue/$reportId': {
      id: '/_authenticated/revenue/$reportId'
      path: '/revenue/$reportId'
      fullPath: '/revenue/$reportId'
      preLoaderRoute: typeof AuthenticatedRevenueReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts/$payoutId': {
      id: '/_authenticated/payouts/$payoutId'
      path: '/payouts/$payoutId'
      fullPath: '/payouts/$payoutId'
      preLoaderRoute: typeof AuthenticatedPayoutsPayoutIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/stats/': {
      id: '/_authenticated/vendor/stats/'
      path: '/vendor/stats'
      fullPath: '/vendor/stats'
      preLoaderRoute: typeof AuthenticatedVendorStatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/profile/': {
      id: '/_authenticated/vendor/profile/'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof AuthenticatedVendorProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/payouts/': {
      id: '/_authenticated/vendor/payouts/'
      path: '/vendor/payouts'
      fullPath: '/vendor/payouts'
      preLoaderRoute: typeof AuthenticatedVendorPayoutsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/stats/report': {
      id: '/_authenticated/vendor/stats/report'
      path: '/vendor/stats/report'
      fullPath: '/vendor/stats/report'
      preLoaderRoute: typeof AuthenticatedVendorStatsReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/stats/$stats': {
      id: '/_authenticated/vendor/stats/$stats'
      path: '/vendor/stats/$stats'
      fullPath: '/vendor/stats/$stats'
      preLoaderRoute: typeof AuthenticatedVendorStatsStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/payouts/$payoutid': {
      id: '/_authenticated/vendor/payouts/$payoutid'
      path: '/vendor/payouts/$payoutid'
      fullPath: '/vendor/payouts/$payoutid'
      preLoaderRoute: typeof AuthenticatedVendorPayoutsPayoutidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPayoutsPayoutIdRoute: typeof AuthenticatedPayoutsPayoutIdRoute
  AuthenticatedRevenueReportIdRoute: typeof AuthenticatedRevenueReportIdRoute
  AuthenticatedRevenueListRoute: typeof AuthenticatedRevenueListRoute
  AuthenticatedVendorsVendorIdRoute: typeof AuthenticatedVendorsVendorIdRoute
  AuthenticatedRevenueManualLazyRoute: typeof AuthenticatedRevenueManualLazyRoute
  AuthenticatedRevenueUploadLazyRoute: typeof AuthenticatedRevenueUploadLazyRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedPlatformsIndexRoute: typeof AuthenticatedPlatformsIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedPayoutsIndexLazyRoute: typeof AuthenticatedPayoutsIndexLazyRoute
  AuthenticatedVendorPayoutsPayoutidRoute: typeof AuthenticatedVendorPayoutsPayoutidRoute
  AuthenticatedVendorStatsStatsRoute: typeof AuthenticatedVendorStatsStatsRoute
  AuthenticatedVendorStatsReportRoute: typeof AuthenticatedVendorStatsReportRoute
  AuthenticatedVendorPayoutsIndexRoute: typeof AuthenticatedVendorPayoutsIndexRoute
  AuthenticatedVendorProfileIndexRoute: typeof AuthenticatedVendorProfileIndexRoute
  AuthenticatedVendorStatsIndexRoute: typeof AuthenticatedVendorStatsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPayoutsPayoutIdRoute: AuthenticatedPayoutsPayoutIdRoute,
  AuthenticatedRevenueReportIdRoute: AuthenticatedRevenueReportIdRoute,
  AuthenticatedRevenueListRoute: AuthenticatedRevenueListRoute,
  AuthenticatedVendorsVendorIdRoute: AuthenticatedVendorsVendorIdRoute,
  AuthenticatedRevenueManualLazyRoute: AuthenticatedRevenueManualLazyRoute,
  AuthenticatedRevenueUploadLazyRoute: AuthenticatedRevenueUploadLazyRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedPlatformsIndexRoute: AuthenticatedPlatformsIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedPayoutsIndexLazyRoute: AuthenticatedPayoutsIndexLazyRoute,
  AuthenticatedVendorPayoutsPayoutidRoute:
    AuthenticatedVendorPayoutsPayoutidRoute,
  AuthenticatedVendorStatsStatsRoute: AuthenticatedVendorStatsStatsRoute,
  AuthenticatedVendorStatsReportRoute: AuthenticatedVendorStatsReportRoute,
  AuthenticatedVendorPayoutsIndexRoute: AuthenticatedVendorPayoutsIndexRoute,
  AuthenticatedVendorProfileIndexRoute: AuthenticatedVendorProfileIndexRoute,
  AuthenticatedVendorStatsIndexRoute: AuthenticatedVendorStatsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EulaRoute: EulaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
